version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/unamegen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip
brews:
  - repository:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: "{{ .ProjectName }}"
    directory: Formula
    commit_msg_template: "build: update formulae to version {{ .Tag }}"
    homepage: "https://thde.io/{{ .ProjectName }}"
    description: Generate user names with ease
    license: MIT
