# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unamegen < Formula
  desc "Generate user names with ease"
  homepage "https://thde.io/unamegen"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thde/unamegen/releases/download/v0.4.0/unamegen_0.4.0_darwin_amd64.tar.gz"
      sha256 "0e8a375bd729dada3ed6f71055e0aeb14bcb896f6db48d5b7d6266408f4f7fd1"

      define_method(:install) do
        bin.install "unamegen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thde/unamegen/releases/download/v0.4.0/unamegen_0.4.0_darwin_arm64.tar.gz"
      sha256 "f1033c964bc53547b2a420594d13b65c09a7f63106e7c461a75f22e3309ea4f9"

      define_method(:install) do
        bin.install "unamegen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thde/unamegen/releases/download/v0.4.0/unamegen_0.4.0_linux_amd64.tar.gz"
      sha256 "9140d96a4754c0d76960cf788a69e894ee860706c50754ae2b46f3348975a1bc"
      define_method(:install) do
        bin.install "unamegen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thde/unamegen/releases/download/v0.4.0/unamegen_0.4.0_linux_arm64.tar.gz"
      sha256 "8a39d81a91c9cdd2f48982d6f522626cf10543abb039d61fe7268796ae0878a9"
      define_method(:install) do
        bin.install "unamegen"
      end
    end
  end
end
