name: web

on:
  push:
    branches:
      - main
  pull_request:

env:
  # https://github.com/tinygo-org/tinygo/releases
  TINYGO_VERSION: 0.42.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: install tinygo
        run: |
          cd $(mktemp -d)
          curl -sLo tinygo.deb https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/tinygo_${TINYGO_VERSION}_amd64.deb
          sudo dpkg -i tinygo.deb
          tinygo version
      - run: make web
      - uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy public --project-name=${{ github.event.repository.name }}
